version: 3.0.{build}
image: Visual Studio 2022
configuration: Release

environment:
  packageVersion: 3.0

cache: 
- source\packages -> **\packages.config

before_build:
- appveyor-retry dotnet restore DemoMap\DemoMap.sln

build:
  project: DemoMap\DemoMap.sln  
  verbosity: normal
  
init:
- ps: $env:buildVersion = "$env:packageVersion.$env:appveyor_build_number"
- ps: $env:nugetVersion = "$env:packageVersion.$env:appveyor_build_number"
- ps: Update-AppveyorBuild -Version $env:buildVersion

dotnet_csproj:
  patch: true 
  file: 'Directory.Build.props'
  assembly_version: '{version}'
  file_version: '{version}'
  
nuget:
  account_feed: false
  project_feed: false
  
artifacts:
- path: source\bin\Release
  name: Release
